Updated map bounding box order for community app
IN-CORE/incore-helm pull request #109
Opened 2024-02-28 16:40 UTC by ywkim312

2024-02-28 16:42 UTC, longshuicy commented on playbook-configs/joplin/map.config.json
> +  "MAX_ZOOM": 15,
This should be 19?

2024-02-28 16:42 UTC, longshuicy requested changes

2024-02-28 16:42 UTC, longshuicy commented on playbook-configs/galveston/map.config.json
> +  "MAX_ZOOM": 15,
This needs to be 19

2024-02-28 16:42 UTC, longshuicy commented on playbook-configs/slc/map.config.json
> +  "MAX_ZOOM": 15,
Same

2024-02-28 16:49 UTC, ywkim312 commented on playbook-configs/galveston/map.config.json
> +  "MAX_ZOOM": 15,
updated

2024-02-28 16:54 UTC, ywkim312 commented on playbook-configs/slc/map.config.json
> +  "MAX_ZOOM": 15,
updated

2024-02-28 17:26 UTC, longshuicy approved these changes

2024-02-29 18:14 UTC, navarroc approved these changes

2024-02-29 18:24 UTC, merged