205 deploy approval app
IN-CORE/incore-helm pull request #206
Opened 2024-12-20 20:19 UTC by longshuicy

In a time crunching to test this app hence missing a few things:
- I didn't put some of the values as secret 
- Missing changelog 
- Missing Notes
- Missing chart.yaml

2025-01-02 20:59 UTC, ywkim312 requested changes

2025-01-02 20:59 UTC, ywkim312 commented on values.yaml
> +    tag: latest
maybe we can change it to the real value instead of latest?

2025-01-02 20:59 UTC, ywkim312 commented on values.yaml
> +  ADMIN_LIST: jonglee1@illinois.edu,cmnavarr@illinois.edu
let's not put the real emails in the repository? We can put this in values-incore-*.yaml

2025-01-02 20:59 UTC, ywkim312 commented on values.yaml
> +  SMTP_SERVER: outbound-relays.techservices.illinois.edu
Maybe we can put the pseudo email and server in this and put the real values in values-incore-*.yaml?

2025-01-02 21:01 UTC, ywkim312 requested changes

2025-01-02 21:01 UTC, ywkim312 commented on templates/approval/deployment.yaml
> +              {{- if .Values.approval.KEYCLOAK_PASSWORD }}
let not put the direct insert of KEYCLOAK password in here, instead just make it only to use the secret like you put below

2025-01-02 21:14 UTC, longshuicy commented on values.yaml
> +    tag: latest
Updated to "master" since incore dev-script repo still uses "master" as the main branch.

2025-01-02 21:15 UTC, longshuicy commented on values.yaml
> +  ADMIN_LIST: jonglee1@illinois.edu,cmnavarr@illinois.edu
Removed and updated in this PR https://git.ncsa.illinois.edu/kubernetes/clusters/incore-dev/-/merge_requests/13/diffs

I don't think we will use values overwrite anymore moving on? hence I left that out.

2025-01-02 21:15 UTC, longshuicy commented on values.yaml
> +  SMTP_SERVER: outbound-relays.techservices.illinois.edu
Same as above.

2025-01-02 21:16 UTC, longshuicy commented on templates/approval/deployment.yaml
> +              {{- if .Values.approval.KEYCLOAK_PASSWORD }}
but I would need to overwrite it with production keycloak password on dev, hence I have this additional logic.

2025-01-02 21:20 UTC, ywkim312 commented on templates/approval/deployment.yaml
> +              {{- if .Values.approval.KEYCLOAK_PASSWORD }}
dev and prod uses different secret so you can set it in there, instead of directly put

2025-02-07 20:33 UTC, jonglee1 approved these changes

2025-02-17 15:47 UTC, ywkim312 approved these changes

2025-02-17 15:47 UTC, merged